global:
    scrape_interval: 2s
    external_labels:
      monitor: 'monitoring'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['prometheus:9090']

    - job_name: 'node'
      static_configs:
        - targets: ['node-exporter:9100']

    - job_name: 'app'
      static_configs:
        - targets: ['localhost:9000', 'localhost:9001']