db:
  host: "localhost"
  port: "5432"
  user: "test"
  password: "test"
  dbname: "postgres"
  sslmode: "disable"

http_server:
  port: "8080"

grpc_server:
  port: ":9000"

grpc_client:
  port: ":9001"
